apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  labels:
    app: {{ .Values.appName }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backendPort }}
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backendSecretName }}
                  key: MONGO_URL
