apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend-service
  labels:
    app: {{ .Values.appName }}-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}
