# .github/workflows/docker-build-push.yml

name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: shirish1612/todo_ngnix

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- Backend Image ---
      - name: Build Backend Docker image
        run: |
          docker build -t $DOCKER_REPO:backend-v1 ./api

      - name: Push Backend Docker image
        run: |
          docker push $DOCKER_REPO:backend-v1

      # --- Frontend Image ---
      - name: Build Frontend Docker image
        run: |
          docker build -t $DOCKER_REPO:frontend-v1 ./client

      - name: Push Frontend Docker image
        run: |
          docker push $DOCKER_REPO:frontend-v1
